Adiciona consulta por group_by / having
saranicoly/viagem-no-tempo pull request #1
Opened 2022-10-16 14:17 UTC by saranicoly

2022-10-19 08:13 UTC, mateuseap approved these changes

2022-10-19 11:20 UTC, nathaliafab approved these changes

2022-10-19 19:06 UTC, mluisass commented on Projeto Físico/consultas.sql
> +HAVING extract(year from DATA_DESTINO)=1856;
Essa filtragem deveria ser feita antes do agrupamento, usando WHERE

```suggestion
WHERE extract(year from DATA_DESTINO)=1856;
```
Pra manter o HAVING, a filtragem deveria ser sobre o agrupamento. Por exemplo, [...] com quantidade de passagens para o destino maior que X

2022-10-19 19:11 UTC, aalmds requested changes

2022-10-19 19:11 UTC, aalmds commented on Projeto Físico/consultas.sql
> +HAVING extract(year from DATA_DESTINO)=1856;
Concordo com Malu, além disso, na consulta tu não faz exatamente a descrição, porque tu projeta o ano além da quantidade de passagens. 

Poderia mudar para: projetar a quantidade de passagens para um local de destino num determinado ano quando houvesse mais do que duas passagens, por exemplo.

2022-10-22 21:45 UTC, aalmds approved these changes

2022-10-22 21:46 UTC, merged