Criação de uma consulta utilizando a cláusula 'inner join'
saranicoly/viagem-no-tempo pull request #4
Opened 2022-10-19 08:09 UTC by mateuseap

## O que eu fiz
- Criei uma consulta utilizando a cláusula `inner join`.

### Descrição da consulta

A ideia dessa consulta é projetar o **Local de Destino** e a **Data de Destino** de uma `Passagem` juntamente com o **nome** do `Cliente` que adquiriu essa `Passagem` e o **nome** do `Funcionário` que realizou a _venda_ da mesma. Essa `Passagem` precisa necessariamente já ter sido utilizada em uma `Viagem`, o `Funcionário` que vendeu a `Passagem` não pode ser _gerente_ de um `Setor` que seja da categoria '**VIAGEM**' e o `Cliente` que detém essa `Passagem` não pode ter realizado a compra de mais do que _2 passagens_. Isso deve ser exibido em uma _ordem decrescente_ de acordo com a **Data de Destino** da `Passagem`.

### Detalhamento do código

- [x] Projetando as colunas desejadas;
```sql
SELECT P.LOCAL_DESTINO AS "LOCAL DE DESTINO", P.DATA_DESTINO AS "DATA", C.NOME AS "CLIENTE", F.NOME AS "FUNCIONÁRIO"
```

- [x] Realizando dois `inner join` para poder pegar o **nome** do Cliente e o **nome** do Funcionário. Como essas informações não estão contidas na tabela `Passagem`, é necessário fazer `inner join` com a tabela `Cliente` e a tabela `Funcionário` para assim termos acesso a esses nomes;
```sql
FROM PASSAGEM P INNER JOIN CLIENTE C ON (P.CLIENTE = C.CPF)
     INNER JOIN FUNCIONARIO F ON (P.FUNCIONARIO = F.CPF)
```

- [x] Utilizando de uma `sub-consulta` para verificar se o **código** da `Passagem` está atrelado a alguma `Viagem`;
```sql
WHERE P.CODIGO_RESERVA IN (SELECT CODIGO_PASSAGEM
                           FROM VIAGEM)
```

- [x] Utilizando de mais uma `sub-consulta`, dessa vez para verificar se o `Funcionário` atrelado a essa determinada `Passagem` não é _gerente_ de um `Setor` que é da categoria '**VIAGEM**';
```sql
      AND P.FUNCIONARIO NOT IN (SELECT CPF
                                FROM SETOR S
                                WHERE S.CATEGORIA LIKE 'VIAGEM')
```

- [x] Realizando a última `sub-consulta` para verificar se o `Cliente` que detém essa determinada `Passagem` não comprou mais do que _2 passagens_;
```sql
      AND P.CLIENTE IN (SELECT CLIENTE
            			FROM PASSAGEM
            			GROUP BY CLIENTE
            			HAVING COUNT(CODIGO_RESERVA) < 3)
```

- [x] Por fim, utilizando um `order by` para ordenar em uma _ordem decrescente_ de acordo com a **Data de Destino** da `Passagem`.
```sql
ORDER BY P.DATA_DESTINO DESC
```

### Output gerado pela consulta

Rodei o script de [**criação de tabelas**](https://github.com/mateuseap/viagem-no-tempo/blob/master/Projeto%20Físico/criação%20de%20tabelas.sql) contido no nosso repositório para criar as tabelas do meu **BD**, depois alterei o script de **povoamento** e rodei ele como as minhas alterações para poder popular o meu **BD** (o script de **povoamento** modificado está na PR #3) e por fim, ao rodar a minha consulta, obtive o seguinte _output_:

![output](https://user-images.githubusercontent.com/52019009/196633527-f945b8e8-eaec-4c3b-b30a-c69a3bc1d8ff.png)

2022-10-19 11:46 UTC, nathaliafab approved these changes

2022-10-19 19:52 UTC, aalmds requested changes
Apesar da consulta ser MUITO boa, acredito que seja muito complicada para o contexto.

2022-10-19 23:19 UTC, SarahLMelo approved these changes
Achei meio complicadinho, mas a consulta em si parece está certinha

2022-10-22 21:55 UTC, aalmds approved these changes

2022-10-22 21:55 UTC, merged